config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "homes#about"
  get 'about'=>'homes#about'
  get 'food_limit'=>'stocks#limit'
  resources :foods do
    resource :likes, only: [:create, :destroy]
  end
  # 食材のソート foodコントローラにsearchアクションを作る→結局表示する場所indexでは
  get 'foods/index/sort_like', to: 'foods#search', as: 'sort_like'
  get 'foods/index/sort_new', to: 'foods#search', as: 'sort_new'
  get 'foods/index/sort_old', to: 'foods#search', as: 'sort_old'
  # 食材のソートここまで
  resources :lists, except: [:show]
  resources :users, only: [:show, :edit, :update]
  resources :stocks
  resources :categories, except: [:show, :new]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!
  # ログイン前でもトップページが見れる

  def top
  end

  def about
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/homes/_list_and_limit.html.erb
<h3><i class="fas fa-clipboard-list mx-3"></i>お買いものリスト</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>食材</th>
      <th></th>
      <th class="text-nowrap">編集</th>
      <th class="text-nowrap">追加</th>
      <th class="text-nowrap">削除</th>
    </tr>
  </thead>
<% lists.each do |list| %>
  <tbody>
    <tr>
      <td class="text-nowrap mx-3 text-left"><%= list.food.name %></td>
      <td><p>×<%= list.amount %></p>

      <td><!--編集-->
        <%= render "lists/edit_amount_btn", list: list %>
      </td>

      <td><!--ストック追加-->
        <%= render "lists/add_stock_btn", list: list %>
      </td>
      <td><!--削除-->
        <%= link_to list_path(list.id),method: :delete, class:"btn btn-sm btn-secondary", data:{confirm: "#{list.food.name}を削除しますか？"} do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </td>
    </tr>
  </tbody>
<% end %>
</table>
<div class="row">
  <div class="row pb-3" style="margin-left:auto;">
    <%= link_to "すべて見る", lists_path, class:"btn btn-sm btn-outline-secondary btn-green" %>
  </div>
</div>
<div class="row mt-3">
  <h3><i class="fas fa-hourglass-half mx-3"></i>期限一覧</h3>
</div>
<div class="row">
  <%= render 'stocks/limit_index', stocks: stocks %>
  <div class="row pb-3" style="margin-left:auto;">
    <%= link_to "すべて見る", food_limit_path, class:"btn btn-sm btn-outline-secondary btn-green" %>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container pb-5">
  <div class="row mb-3">
    <font size="5">
      まだ食べられるものを、食べられるうちに使い切ろう。<br>
      <b>Check Stock</b>は、各家庭の食材のストックを適正に保つお手伝いをします！
    </font>
  </div>
  <div class="row">
    <h4 class="mt-3"><strong>使い方</strong></h4>
  </div>
  <div class="row">
    <p>まずは、<%= link_to "食材一覧", foods_path %>から食材を追加しましょう！
      名前とカテゴリを入力して登録します。<br>
      その後、<%= link_to "ストック", stocks_path %>に追加することで
      家にある食材として登録することができます。<br>
      先に食材を追加しておくと
      より便利に使えるようになります！<br>
      </p>
  </div>
  <div class="row">
    <h4 class="mt-3"><strong>活用シーン</strong></h4>
  </div>
  <div class="row pb-5">
    <div class="col-6">
      <%= image_tag 'memo_color.png', width: '300px', height: '225px' %>
      <p class="mt-3">買い物メモを書いたけど、ほかに買い足すものはあったかな？<br>
      そんな時には→<%= link_to "お買い物リスト", lists_path %></p>
    </div>
    <div class="col-6">
      <%= image_tag 'cooking_color.png', width: '300px', height: '225px' %>
      <p class="mt-3">期限の近い食材から調理したい！<br>
      そんな時には→<%= link_to "期限一覧", food_limit_path %></p>
    </div>
  </div>
  <div class="row pb-5">
    <div class="col-6">
      <%= image_tag 'shopping_man_color.png', width: '250px', height: '225px' %>
      <p class="mt-3">冷蔵庫の中を確認せずに買い物に来ちゃった！<br>
      そんな時には→<%= link_to "ストック一覧", stocks_path %></p>
    </div>
    <div class="col-6">
      <%= image_tag 'cannnotdecide_woman_color.png', width: '140px', height: '225px' %>
      <p class="mt-3">家に残っている食材から今日の献立を考えたいな・・・<br>
      そんな時には→<%= link_to "ストック一覧", stocks_path %></p>
    </div>
  </div>




</div>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>