config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "homes#about"
  get 'about'=>'homes#about'
  get 'food_limit'=>'stocks#limit'
  resources :foods do
    resource :likes, only: [:create, :destroy]
  end
  # 食材のソート foodコントローラにsearchアクションを作る→結局表示する場所indexでは
  get 'foods/index/sort_like', to: 'foods#search', as: 'sort_like'
  get 'foods/index/sort_new', to: 'foods#search', as: 'sort_new'
  get 'foods/index/sort_old', to: 'foods#search', as: 'sort_old'
  # 食材のソートここまで
  resources :lists, except: [:show]
  resources :users, only: [:show, :edit, :update]
  resources :stocks
  resources :categories, except: [:show, :new]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/food.rb
class Food < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :lists, dependent: :destroy
  belongs_to :user
  belongs_to :category

  validates :name, presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  # scope :like, -> {order(created_at: :desc)} わからないのでとりあえず後回し
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[show edit destroy update]
  before_action :is_matching_login_user, only: %i[edit update]

  def index
    set_index
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    if @food.save
      redirect_to request.referer,notice:"食材を登録しました!"
    else
      set_index
      render :index
    end
  end

  def destroy
    @food.destroy
    redirect_to request.referer, notice: "食材を削除しました"
  end

  def show
  end

  def edit
  end

  def update
    if @food.update(food_params)
      redirect_to request.referer, notice: "編集が完了しました"
    else
      set_index
      render :index
    end
  end
private
  def food_params
    params.require(:food).permit(:name, :user_id, :category_id)
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def set_food
    @food = Food.find(params[:id])
  end

  def set_index
    @food_new = Food.new
    @category_new = Category.new
    @lists = current_user.lists.limit(5)
    @stocks_limit = current_user.stocks.order(limit: "ASC").limit(5)
    @categories = current_user.categories
      if params[:category_id]
        @category = Category.find(params[:category_id])
        @foods = @category.foods.page(params[:page]).per(10)
      else
        @foods = current_user.foods.page(params[:page]).per(10)
      end

      if params[:new]
        @foods = Food.latest.page(params[:page]).per(PER_PAGE)
      elsif params[:old]
        @foods = Food.old.page(params[:page]).per(PER_PAGE)
      end
  end

  def is_matching_login_user
    user_id = @food.user_id
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to root_path, alert: '他のユーザーの情報は編集できません。'
    end
  end


end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_add_list_btn.html.erb
<div class="position-relative">
  <%= link_to "#list_add-item-#{food.id}", class:"btn btn-sm btn-outline-secondary", "data-toggle": "collapse", role: "button", "aria-expanded": "false", "area-controls": "list_add-item-#{food.id}", style: "z-index:1;" do %>
    <i class="fas fa-clipboard-list"></i> 追加
  <% end %>
  <div class="collapse position-absolute" id="list_add-item-<%= food.id %>" style="left:60px; z-index:2;">
    <div class="card card-body">
      <%= form_with(model: food.lists.build, local: true) do |f| %>
        <%= f.hidden_field :food_id %>
      <div class="form-row align-items-baseline">
        <%= f.label :amount, "個数　" %>
        <%= f.number_field :amount , style: "width:50px;" %>
      </div>
      <!--ここから単位-->
      <!--単位終わり-->
      <div class="form-row justify-content-center align-items-baseline">
        <%= f.submit 'お買いものリストへ追加',class:"btn btn-sm btn-orange mt-1" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/foods/_add_stock_btn.html.erb
<div class="position-relative">
<%= link_to "#stock_add-item-#{food.id}", class:"btn btn-sm btn-outline-secondary", "data-toggle": "collapse", role: "button", "aria-expanded": "false", "area-controls": "stock_add-item-#{food.id}", style: "z-index:1;" do %>
  <i class="fas fa-cubes"></i> 追加
<% end %>
<div class="collapse position-absolute" id="stock_add-item-<%= food.id %>" style="left:-145px; z-index:2;">
    <div class="card card-body">
      <%#= render 'foods/add_form', model: food.stocks.build %>
      <%= form_with(model: food.stocks.build, local: true) do |f| %>
      <!--↑アソシエーションの記述があればbuildで作れる-->
        <%= f.hidden_field :food_id %>
        <%= f.hidden_field :category_id, value: food.category_id %>
      <div class="form-row align-items-baseline">
        <%= f.label :amount, "個数　" %>
        <%= f.number_field :amount , style: "width:50px;" %>
      </div>
      <!--ここから単位-->
      <!--単位終わり-->
      <div class="form-row align-items-baseline">
        <%= f.label :buy_day, "購入日" %>
        <%= f.date_field :buy_day %>
      </div>
      <div class="form-row align-items-baseline">
        <%= f.label :limit, "期限　" %>
        <%= f.date_field :limit %>
      </div>
        <%= f.text_area :memo,placeholder: '備考欄' %>
      <div class="form-row justify-content-center align-items-baseline">
        <%= f.submit 'ストックに追加する',class:"btn btn-sm btn-orange mt-1" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/foods/_edit_btn.html.erb
<div class="position-relative">
  <%= link_to "#food_edit-item-#{food.id}", class:"btn btn-sm btn-outline-secondary", "data-toggle": "collapse", role: "button", "aria-expanded": "false", "area-controls": "food_edit-item-#{food.id}", style: "z-index:3;" do %>
    <i class="fas fa-edit"></i>
  <% end %>
<div class="collapse position-absolute" id="food_edit-item-<%= food.id %>" style="z-index:2;">
  <!--idをボタンごとに変えないと押していないところでも動いてしまう-->
    <div class="card card-body">
      <%= form_with model: food, method: :patch,local: true do |f| %>
      <div class="form-row align-items-baseline">
        <%= f.label :name, "食材名" %>
        <%= f.text_field :name, autocomplete: "name",placeholder: '食材名を入力' %>
      </div>
      <div class="form-row align-items-baseline">
        <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: "-- カテゴリを選択 --" %>
      </div>
      <!--ここから単位-->
      <!--単位終わり-->
        <%= f.submit "編集内容を登録",class:"btn btn-sm btn-orange mt-1" %>
      <% end %>
    </div>
  </div>
</div>

app/views/foods/_form.html.erb
<%= form_with model: food, url: foods_path, local:true do |f| %>
  <%= f.text_field :name, autocomplete: "name",placeholder: '食材名を入力', class:"ml-3"%>
  <%= f.collection_select :category_id, @categories = current_user.categories, :id, :name, include_blank: "-- カテゴリを選択 --" %><br>
  <%= f.submit "食材を登録",class:"btn btn-sm btn-outline-secondary btn-green m-3" %>
<% end %>

app/views/foods/index.html.erb
<div class="container pb-5">
<div class="alert">
  <% if @food %>
    <%= @food.errors.count %>件のエラーが発生しました
    <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% elsif @stock %>
    <%= @stock.errors.count %>件のエラーが発生しました
    <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% elsif @list %>
    <%= @list.errors.count %>件のエラーが発生しました
    <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

  <div class="row"><!--全体を囲み横並びにするrow-->
    <!--お買いものリスト&期限一覧はスマホサイズは非表示にしてヘッダーからアクセスさせる-->
    <div class="d-none d-lg-block col-md-4 mt-3 pb-5">
      <%= render 'homes/list_and_limit', lists: @lists, stocks: @stocks_limit %>
    </div>

    <div class="col-md-7 offset-1 pb-5"><!--追加した-->
      <div>
        <div class="row justify-content-center mt-3">
          <h3 class="text-center"><i class="fas fa-carrot mx-3"></i>食材一覧</h3>
          <span class="mx-3"><%= link_to "ストック一覧へ",stocks_path, class:"btn btn-sm btn-outline-secondary" %></span>
        </div>
        <div class="row justify-content-center">
          <p class="text-center ">食材名をクリックすると詳細・編集画面へ 追加はページ下部</p>
        </div>
        <div class="row justify-content-center mb-2">
          <%= render 'categories/btn', categories: @categories %>
        </div>
        <div class="row justify-content-center pb-5">
          <div class="sort">
            <%= link_to '新しい順', foods_path(new: 'true'), {class: 'sort-link' "#{'active' if current_page?('foods/index?new=true')}"} %>
          </div>
          <table class="table table-hover justify-content-center mx-5 pb-5">
            <tr>
              <th></th>
              <th>食材</th>
              <th>ストックへ</th>
              <th>お買いものリストへ</th>
              <th>削除</th>
            </tr>
            <% @foods.each do |food| %>
              <tbody>
              <tr>
                <td id="like_btn_<%= food.id %>">
                  <%= render "likes/btn", food: food %>
                </td>
                <td class="text-left">
                  <%= link_to food_path(food.id) do %>
                    <%= food.name %>
                  <% end %>
                  <p class="col-1 text-nowrap">在庫:<%= food.stocks.any? ? "○" : "×" %></p>
                </td>
                <td>
                  <%= render "foods/add_stock_btn", food: food %>
                </td>
                <td>
                  <%= render "foods/add_list_btn", food: food %>
                </td>
                <td>
                  <%= link_to food_path(food.id),method: :delete, class:"btn btn-sm btn-secondary", data:{confirm: "#{food.name}を削除しますか？"} do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </td>
              </tr>
            </tbody>
            <% end %>
          </table>
          <%= paginate @foods %>
        </div>
      </div>
      <div class="row justify-content-center">
        <h3 class="text-right pb-3"><i class="fas fa-plus mx-3"></i>カテゴリ・食材の追加</h3>
      </div>
      <div class="row justify-content-center">
        <p class="text-center ">カテゴリを追加してから食材名を追加しよう</p>
      </div>
      <div class="row justify-content-center">
        <div class="text-center mt-3 pb-3">
          <div class="pb-3">
            <h4 class="text-nowrap"><i class="fas fa-align-justify mr-1"></i>カテゴリの追加</h4>
            <%= render 'categories/form', category: @category_new %>
          </div>
        </div>
        <div class="text-center mt-3 pb-3">
          <h4><i class="fas fa-carrot mr-1"></i>食材の追加</h4>
          <%= render 'foods/form', food: @food_new %>
        </div>
      </div>
    </div>
  </div>
</div><!--全体のrow-->

app/views/foods/show.html.erb
<div class="container pb-5">
  <div class="row">
    <h3 class="col-4">食材の詳細</h3>
    <span class="col-1 offset-2">
      <%= render "edit_btn", food: @food %>
    </span>
    <span class="col-3"><%= link_to "一覧へ戻る", foods_path, class:"btn btn-sm btn-outline-secondary" %></span>
    <span>
      <%#= link_to food_path,method: :delete, class:"btn btn-sm btn-outline-secondary", data:{confirm: "#{food.name}を削除しますか？"} do %>
        <!--<i class="fas fa-trash-alt"></i>-->
      <%# end %>
      <%#= link_to "削除",food_path(@food.id),method: :delete, class:"btn btn-sm btn-outline-secondary", data:{confirm: "#{food.name}を削除しますか？"} %>
    </span>
  </div>
  <table class="mt-3">
    <tr>
      <th class="col-1">食材名</th>
      <td class="col-3"><%= @food.name %></td>

    </tr>
    <tr>
      <th class="col-1">カテゴリ</th>
      <td class="col-3"><%= @food.category.name %></td>
    </tr>
  </table>
</div>