config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "homes#about"
  get 'about'=>'homes#about'
  get 'food_limit'=>'stocks#limit'
  resources :foods do
    resource :likes, only: [:create, :destroy]
  end
  # 食材のソート foodコントローラにsearchアクションを作る→結局表示する場所indexでは
  get 'foods/index/sort_like', to: 'foods#search', as: 'sort_like'
  get 'foods/index/sort_new', to: 'foods#search', as: 'sort_new'
  get 'foods/index/sort_old', to: 'foods#search', as: 'sort_old'
  # 食材のソートここまで
  resources :lists, except: [:show]
  resources :users, only: [:show, :edit, :update]
  resources :stocks
  resources :categories, except: [:show, :new]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods, dependent: :destroy
  has_many :stocks
  belongs_to :user
  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[destroy update]
  before_action :is_matching_login_user, only: %i[edit update]

  def index
    set_index
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    if @category.save
      redirect_to categories_path, notice: "カテゴリが新規登録されました"
    else
      set_index
      render :index
    end
  end

  def destroy
    @category.destroy
    redirect_to request.referer, notice: "カテゴリを削除しました"
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to request.referer, notice: "カテゴリを編集しました"
  end
private
  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def set_index
    @categories = current_user.categories
    @category_new = Category.new
  end

  def is_matching_login_user
    user_id = @category.user_id
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to root_path, alert: '他のユーザーの情報は編集できません。'
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_btn.html.erb
<%= link_to "ALL",foods_path, class:"btn btn-sm btn-outline-secondary m-1 btn-category"%>
<% categories.each do |category| %>
  <%= link_to category.name,foods_path(category_id: category.id), class:"btn btn-sm btn-outline-secondary m-1 btn-category" %>
<% end %>

app/views/categories/_form.html.erb
<%= link_to "カテゴリ一覧・追加", categories_path, class:"btn btn-sm btn-outline-secondary mt-1" %>
<%= form_with model: category, url: categories_path, local:true do |f| %>
  <%= f.text_field :name, autocomplete: "name",placeholder: 'カテゴリ名を入力' %>
  <%= f.submit "カテゴリを登録",class:"btn btn-sm btn-outline-secondary btn-green m-3" %>
<% end %>

app/views/categories/index.html.erb
<div class="container pb-5">
  <div class="alert">
    <% if @category %>
      <%= @category.errors.count %>件のエラーが発生しました
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row justify-content-center pb-3">
    <h3><i class="fas fa-align-justify mr-1"></i>カテゴリ一覧・追加</h3>
    <span class="mx-3"><%= link_to "食材一覧へ",foods_path, class:"btn btn-sm btn-outline-secondary" %></span>
    <span><%= link_to "ストック一覧へ",stocks_path, class:"btn btn-sm btn-outline-secondary" %></span>
  </div>
  <div class="row pb-5 mb-5">
    <div class="col-md-4 mt-3">

      <div>
        <h4>カテゴリの追加</h4>
        <%= form_with model: @category_new, url: categories_path, local:true do |f| %>
          <div class="form-row justify-content-center align-items-baseline">
            <%= f.text_field :name, autocomplete: "name",placeholder: 'カテゴリ名を入力' %>
          </div>
          <div class="form-row justify-content-center align-items-baseline">
            <%= f.submit "カテゴリを登録",class:"btn btn-sm btn-outline-secondary btn-green m-3" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-8 mt-3 pb-5">
      <h4>カテゴリ一覧</h4>
      <% @categories.each do |category| %>
        <table class="table table">
          <tbody>
            <tr>
              <td style="width:30%;"><%= category.name %></td>
              <td style="width:35%;">
                <div class="position-relative">
                  <%= link_to "#category_edit-item-#{category.id}", class:"btn btn-sm btn-outline-secondary", "data-toggle": "collapse", role: "button", "aria-expanded": "false", "area-controls": "category_edit-item-#{category.id}", style: "z-index:1;" do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                <div class="collapse position-absolute" id="category_edit-item-<%= category.id %>" style="z-index:2;">
                  <!--idをボタンごとに変えないと押していないところでも動いてしまう-->
                    <div class="card card-body">
                      <%= form_with model: category, method: :patch,local: true do |f| %>
                      <div class="form-row align-items-baseline">
                        <%= f.label :name, "カテゴリ名" %>
                        <%= f.text_field :name, autocomplete: "name",placeholder: 'カテゴリ名を入力' %>
                      </div>
                      <div class="form-row justify-content-center align-items-baseline m-1">
                        <%= f.submit "編集内容を登録",class:"btn btn-sm btn-outline-secondary btn-green m-1" %>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </td>
              <td style="width:35%;">
                <%= link_to category_path(category.id),method: :delete, class:"btn btn-sm btn-secondary", data:{confirm: "カテゴリを削除した場合、紐づいている食材/ストックも消えてしまいます。カテゴリを削除しますか？"} do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>


  </div>
</div>