config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "homes#about"
  get 'about'=>'homes#about'
  get 'food_limit'=>'stocks#limit'
  resources :foods do
    resource :likes, only: [:create, :destroy]
  end
  # 食材のソート foodコントローラにsearchアクションを作る→結局表示する場所indexでは
  get 'foods/index/sort_like', to: 'foods#search', as: 'sort_like'
  get 'foods/index/sort_new', to: 'foods#search', as: 'sort_new'
  get 'foods/index/sort_old', to: 'foods#search', as: 'sort_old'
  # 食材のソートここまで
  resources :lists, except: [:show]
  resources :users, only: [:show, :edit, :update]
  resources :stocks
  resources :categories, except: [:show, :new]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/_footer.html.erb
<footer class="text-center pt-3 pb-1 fixed-bottom" style="background-color:#F7C682;">
  <div class="container">
    <div class="row no-gutters">
      <div class="col">
        <p style="color:#FFF;">使える食材を見直してフードロスを削減しよう!</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color:#EAF2AE;">
    <div class="container">
      <a class="navbar-brand" href="/" style="width:40%">
        <%= image_tag 'CheckStock_logo.png', width: '40%', height: '40%' %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <% if user_signed_in? %><!--会員-->
        <p class="ml-1 text-nowrap" style="color:#EF8C04; text-left">おつかれさま、<br><%= current_user.name %>さん!</p>
        <div><!--マイページ・ログアウト/他の4つと2段にしたい-->
          <ul class="navbar-nav pl-5 ml-5">
            <li>
              <%= link_to user_path(current_user),class: 'nav-link text-nowrap text-light' do %>
                <p class="font-green"><i class="fas fa-info-circle"></i> マイページ</p>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-nowrap text-light',data:{confirm: "ログアウトしますか？"} do %>
                <p class="font-green"><i class="fas fa-sign-out-alt"></i> ログアウト</p>
              <% end %>
            </li>
          </ul>
          <ul class="navbar-nav pl-5 ml-5">
            <li>
              <%=  link_to foods_path,class: 'nav-link text-nowrap text-light' do %>
                <p class="font-orange"><i class="fas fa-carrot"></i> 食材一覧</p>
              <% end %>
            </li>
            <li>
              <%=  link_to stocks_path ,class: 'nav-link text-nowrap text-light' do %>
                <p class="font-orange"><i class="fas fa-cubes"></i> <%= current_user.name %>家のストック</p>
              <% end %>
            </li>
            <!--下2つはlgサイズより大きくなったら表示-->
            <li>
              <%=  link_to lists_path ,class: 'nav-link text-nowrap text-light' do %>
                <p class="font-orange d-lg-none"><i class="fas fa-clipboard-list"></i> お買いものリスト</p>
              <% end %>
            </li>
            <li>
              <%=  link_to food_limit_path ,class: 'nav-link text-nowrap text-light' do %>
                <p class="font-orange d-lg-none"><i class="fas fa-hourglass-half"></i> 期限一覧</p>
              <% end %>
            </li>
          </ul>
        </div>
        <% else %><!--見るだけの人-->
          <ul class="navbar-nav ml-auto">
            <li>
              <%= link_to new_user_registration_path,class: 'nav-link text-nowrap text-light' do %>
                <p class="font-orange"><i class="fas fa-user-plus"></i> 新規登録</p>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path ,class: 'nav-link text-nowrap text-light' do %>
                <p class="font-orange"><i class="fas fa-sign-in-alt"></i>ログイン</p>
              <% end %>
            </li>
            <li>
              <%= link_to users_guest_sign_in_path,class: 'nav-link text-nowrap text-light',method: :post do %>
                <p class="font-orange"><i class="fas fa-eye"></i>ゲストログイン</p>
              <% end %>
            </li>
          </ul>
        <% end %>

      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheckStock</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>